### ISSUE TITLE
problem with extended methods

### ISSUE THREAD

**Issue by jmls** [angelnikolov/ngx-cacheable#13]
I have a  base class which implements find, using <Model> as a generic and a unique url for each model, so a GET to `/api/model1/find` and `/api/model2/find` for example

each model data service extends this base service

however, if I @Cacheable() the `find` method in the base class, then the *same* data is returned from in-memory cache for any model.

ie if I first get `users` , then a subsequent call to `find` in the `customer` model _also_ returns the list of users

The only way I see round this is to override each method in each model, and add a cache at that level but it seems a seriously nasty hack

**Comment by jmls** [comment]
oh unless I supply my own DEFAULT_CACHE_RESOLVER ;) maybe that will work

**Comment by cyberbobjr** [comment]
Hi,
Sorry for the necropost, but does this trick was implemented in the current version of Ngx-cacheable, because it might be usefull for my project :)

**Comment by angelnikolov** [comment]
Yes, it is.
https://github.com/angelnikolov/ngx-cacheable/blob/dc1c2cc90cbd09f9209a82632a161ce49fa12466/common/index.ts#L8

**Comment by cyberbobjr** [comment]
you're great ! many thanks for your job 😄
