### ISSUE TITLE
change default cache resolver

### ISSUE THREAD

**Issue by jmls** [angelnikolov/ngx-cacheable#14]
the default cache resolver simply does a JSON.stringify test against the old and new parameters. This does not take into account the position of the properties and can lead to false results (depending on your point of view). 

If you were to use object-hash to compare the two objects this is no longer an issue. See the code sample below

```
const hash = require('object-hash');

const p1 = { d1: 'd1', d2: 'd2' };
const p2 = { d2: 'd2', d1: 'd1' };

const hash1 = hash(p1);
const hash2 = hash(p2);

console.log('json', JSON.stringify(p1) === JSON.stringify(p2));
console.log('hash', hash1, hash2, hash1 === hash2);

```

the result of this is

> json false
> hash f4c434a0e4c11deb776f4281c9b3848ccbe63578 f4c434a0e4c11deb776f4281c9b3848ccbe63578 true

this could be implemented by default , or by adding an option to specify a different cache resolver so that it won't break existing code that relies on key position creating different cache results

**Comment by angelnikolov** [comment]
There is an option to specify a different cache resolver already. You can just supply a `cacheResolver` to the config.

**Comment by jmls** [comment]
yes, I know, but this allows someone to use the hash resolver with just a simple config option

**Comment by angelnikolov** [comment]
How much does this increase the bundle size of the decorator?

**Comment by jmls** [comment]
master: -rw-rw-r-- 1 jmls jmls  5894 Sep 27 09:06 cacheable.decorator.js
branch:  -rw-rw-r-- 1 jmls jmls  6181 Sep 27 09:59 cacheable.decorator.js

although I forgot to `yarn build` (didn't realise that dist was part of the package)

**Comment by angelnikolov** [comment]
Yeah I was thinking more of the whole footprint of the `object-hash` library. Can you measure it within a real app.. Don't want to increase the footprint for everyone for such a small change :)

**Comment by jmls** [comment]
ok, so I did a `ng new` and added the app.component constructor to read
```
constructor() {
    console.log(foobar123');
  }

```
then did a prod build

> $ ng build --prod
> 
> Date: 2018-09-27T09:11:45.976Z
> Hash: 4b65c350709b5d29e44d
> Time: 16208ms
> chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
> chunk {1} styles.34c57ab7888ec1573f9c.css (styles) 0 bytes [initial] [rendered]
> chunk {2} polyfills.2f4a59095805af02bd79.js (polyfills) 59.6 kB [initial] [rendered]
> chunk {3} main.2001cec6f9fda3d94344.js (main) 172 kB [initial] [rendered]
> Done in 18.49s.
> 
I then added the `object-hash` import , and changed the constructor to read
```
constructor() {
    console.log(hash('foobar123'));
  }
```
and build prod again

> jmls@jmls-MS-7641:/media/jmls/data/development/testhash$ yarn build --prod
> yarn run v1.7.0
> warning ../package.json: No license field
> $ ng build --prod
> 
> Date: 2018-09-27T09:13:13.714Z
> Hash: 33c8205dddc2b6e00526
> Time: 18647ms
> chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
> chunk {1} styles.34c57ab7888ec1573f9c.css (styles) 0 bytes [initial] [rendered]
> chunk {2} polyfills.2f4a59095805af02bd79.js (polyfills) 59.6 kB [initial] [rendered]
> chunk {3} main.90f87ba60061b2818da5.js (main) 208 kB [initial] [rendered]
> Done in 20.90s.

so the whole app bundle size increased from 172K to 208K

**Comment by angelnikolov** [comment]
Let me think about that.. That's quite a jump for a 6kb library. It drags along `crypto` which is pretty big. I feel like the benefit we gain from adding this compare to what we lose is smaller and is something that can be mitigated by a better documentation, i.e - if you want your cache to resolved properly for object parameters, they should have the same shape.

**Comment by Ayushidawada** [comment]
@angelnikolov Can you please give me an example of using cacheResolver and cacheHasher and its difference,As i am using your package for my project,as of now not facing any issue while using other configurations except this two.
