### ISSUE TITLE
Upgrade rxjs version dependency

### ISSUE THREAD

**Issue by zcmander** [angelnikolov/ngx-cacheable#18]
I tried to upgrade my application from Angular 6 to 7 and because ngx-cacheable uses  rxjs version 6.2, it raises an error:

```
λ  ng update @angular/cli @angular/core
                  Package "ngx-cacheable" has an incompatible peer dependency to "rxjs" (requires "6.2.0", would install "6.3.3").
Incompatible peer dependencies found. See above.

```

RXJS change log can be found at: [https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#630-2018-08-30](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#630-2018-08-30)

**Comment by zcmander** [comment]
Using - Force resolve the upgrade issue, altough the original issue stil remains and i can't see the reason not to upgrade.

**Comment by angelnikolov** [comment]
@zcmander 
Are you sure that's caused by `ngx-cacheable`'s dependency? It's listed as a peerDependency of `^6.2.0` so if your other packages allow it, it should properly install 6.3.3? Am I missing something?

**Comment by zcmander** [comment]
Sure it's because of the ngx-cacheable. Npm only issues this one as a warning, so it will install newer version just fine.

Original issue occured when using ng update, so this issue might ne related to that. Anyway, because it is just a warning, to me this issue can be closed, because I can work around it, and I dont really know a lot about of the packaging in node.

**Comment by angelnikolov** [comment]
Got it!
