### ISSUE TITLE
In some url pattern it is not working

### ISSUE THREAD

**Issue by 234akshay** [angelnikolov/ngx-cacheable#19]
api url: products/3?page=1

3: categoryid

in above api url cache response getting empty but normally api call i get response

Api response:
![apiresponse](https://user-images.githubusercontent.com/44695280/47900181-097c2800-dea2-11e8-90ae-54146b3f5361.png)

cached response:
![cachedresponse](https://user-images.githubusercontent.com/44695280/47900186-0c771880-dea2-11e8-99b1-2c0dbc38cd8f.png)

**Comment by angelnikolov** [comment]
Hey @234akshay, can you provide some snippets of code which led to this?

**Comment by 234akshay** [comment]
@Cacheable({
async: true,
maxCacheCount: 1000,
maxAge: 7200000
})
callGetAPI(url: string) {
    return this.http.get<any>(environment.apiUrl + url, this.headers())
      .pipe(map(
        data => {
          return data;
        }
      ));
  }

// this way i am doing it is correct way?

**Comment by angelnikolov** [comment]
And you are calling this twice with the same url?

**Comment by 234akshay** [comment]
no i am calling once at a time but after sometime hit same api it is getting empty data. i don't know but at same time it is calling only once not twice that i am sure.

**Comment by angelnikolov** [comment]
Can you check the network tab and confirm that no 2nd request is sent?
It doesn't make sense that just the data is empty and the rest of the payload is the same..
Also you have some other differences in the payload like `to` and `total` so I guess that's a new request.
I see that you are using one generic method that you maybe use for all `[GET]`s. You are also using a maxCacheCount which should cache `1000` calls. 
It looks like you are calling  different URLs between the first and the second call, and the second payload is coming from the server.
