### ISSUE TITLE
'Cacheable' is not initialized at ngx-cacheable\dist\cacheable.decorator.ts

### ISSUE THREAD

**Issue by rafaelfgx** [angelnikolov/ngx-cacheable#25]
Hello!

First I want to thank you for the great work!

I am having the following error in the latest versions (1.1.0, 1.1.1, 1.1.2, 1.1.3) when running ng serve:

Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'Cacheable'
'Cacheable' references 'Cacheable'
'Cacheable' is not initialized at ngx-cacheable\dist\cacheable.decorator.ts(4,22).

If I change to version 1.0.9, it works normally.

I'm using node 11.12.0 and Angular CLI 7.3.6.

Thank you for you attention.

![image](https://user-images.githubusercontent.com/7357119/54652452-b0e6a980-4a95-11e9-881d-bfe824f54ea2.png)

![image](https://user-images.githubusercontent.com/7357119/54652467-bfcd5c00-4a95-11e9-9792-26d2c0cda707.png)

**Comment by angelnikolov** [comment]
Hm, will try it out and get back to you with a solution. In the meantime it will be really helpful if you create a stackblitz wher this is reproducible :)

**Comment by rafaelfgx** [comment]
I'm trying to simulate the error, but apparently it's something very specific.

**Comment by angelnikolov** [comment]
I will take a look tomorrow. Thanks for the info!

**Comment by rafaelfgx** [comment]
Thank you for your time, I will also make several attempts to discover the error.

**Comment by nico13051995** [comment]
I have the same issue, but only with AOT, version 1.0.9 works great.

**Comment by angelnikolov** [comment]
I think it has something to do with the new function expressions I added as part of the refactor, as mentioned here https://angular.io/guide/aot-compiler#metadata-restrictions
Will try to resolve those asap. Thanks guys!

**Comment by angelnikolov** [comment]
Fixed in https://github.com/angelnikolov/ngx-cacheable/commit/43aa04d8a66a933f3d42aceaf3eaaa2908bbce9a

**Comment by rafaelfgx** [comment]
Well done! Thank you! 👍
