### ISSUE TITLE
Default arguments in functions not working

### ISSUE THREAD

**Issue by fimius23** [angelnikolov/ngx-cacheable#30]
If I have a default argument in a function, and pass `void 0` to the function call, the default argument does not get applied. Looks like your method of cloning parameters turns undefined into null. This time I do have a working example... :)

https://stackblitz.com/edit/angular-gvjnvx?file=src%2Fapp%2Ftest.service.spec.ts

**Comment by angelnikolov** [comment]
Nice one! Fixed and tested. Will publish 1.1.5 in a minute.
