### ISSUE TITLE
cacheBusterNotifier from another service?

### ISSUE THREAD

**Issue by kthomas182** [angelnikolov/ngx-cacheable#34]
Is it possible to set a cacheBusterNotifier from another service?

Ex. 

- Orders (order.service.ts) is cached for 5 minutes.
- I create a new order (order-entry.service.ts).
- When it is successful I want to send a cacheBuster notification to the order.service.ts method for getOrders()

**Comment by angelnikolov** [comment]
Yes, you can just create a third file and create the subject there like:
```
export const notifier = new Subject();
```
Then, where your cache buster service is (orer-entry.service.ts), use it like:
```
import {notifier} from ../where-you-defined-this';

@CacheBuster({
   cacheBusterNotifier: notifier
})
createNewOrder()
```
and in the `order.service.ts` - 
```
import {notifier} from ../where-you-defined-this';

@Cacheable({
   cacheBusterObserver: notifier.asObservable()
})
getOrders()
```

**Comment by angelnikolov** [comment]
@kthomas182, let me know if you got any other questions. Closing this for now :)

**Comment by REHOUMI** [comment]
Hi dear friend, I need your help, can I notify two objects:

const notifier1 = new Subject();
const notifier2 = new Subject();

@CacheBuster({
   cacheBusterNotifier: notifier1, notifier2
})

I want to notify two services.

thank you!

**Comment by REHOUMI** [comment]
I found a solution using this:

//agence.service.ts file
export const agenceCache = new Subject<void>();

//societe.service.ts file
import { agenceCache } from '../../service/agence/agence.service'; 
const societeCache = new Subject<void>();

@CacheBuster({
     cacheBusterNotifier: societeCache,
})
@CacheBuster({
     cacheBusterNotifier: agenceCache,
})
     public updateSociete(societeId: number, societe: Societe) {
     return this.httpClient.put(`${environment.api}/societe/${societeId}`, societe);
}

thank you!
