### ISSUE TITLE
Cache separate by different parameter values

### ISSUE THREAD

**Issue by muratcorlu** [angelnikolov/ngx-cacheable#42]
Is it possible to keep caches for old function parameters too?

```ts
@Cacheable()
getArticle(id: string): Observable<Article> {
  ....
}
```

I call this method several times with different `articleId`s in a view, then none of my requests are being cached actually. My expected behaviour was to cached every article request separately.

**Comment by angelnikolov** [comment]
You can provide a `maxCacheCount` parameter to the `Cacheable` like:
```
@Cacheable({
maxCacheCount: 100})
```
This will make the decorator cache the last 100 calls.

**Comment by muratcorlu** [comment]
OK, I think this'll fulfil my needs. Thanks.
