### ISSUE TITLE
[Question] Can I cache some api call with inner params ?

### ISSUE THREAD

**Issue by marcio199226** [angelnikolov/ngx-cacheable#46]
Hi I will explain my question with simple example:

```
  @Cacheable({
    maxAge: 60000,
    maxCacheCount: 10,
    cacheBusterObserver: entityBustCache$.asObservable()
  })
  list(payload: any = {}): Observable<any> {
    return this._http.post('${environment.baseUrl}/some/api', { ...payload, inner_param: this._someService.getObservable().value });
  }
```

So my question is how can I cache some endpoints with inner params that are not provided by method call? I have tried to cache internal closure with all params but without success

```
  list(payload: any = {}): Observable<any> {
    payload = { inner_param: this._someService.getObservable().value, ...payload };

    @Cacheable({
      maxAge: 60000,
      maxCacheCount: 10,
      cacheBusterObserver: entityBustCache$.asObservable()
    })
    const apiCall = (p) => this._http.post('${environment.baseUrl}/some/api', p)

    return apiCall(payload);
  }
```

Or I have to move all params to method definition in in my case:
```
list(payload: any = {}, inner_param): Observable<any> {
  // code
}
```

Best regards and thanks for this awesome library !

P.S I think that decorators can only decorates methods/properties of class, so maybe we could add an additional param to Cacheable decorator something like this:
```
@Cacheable({
  parameters: {}
})
```

And merge this option before this line https://github.com/angelnikolov/ngx-cacheable/blob/master/cacheable.decorator.ts#L43?
Do you think it could work?

RE P.S

Seems that something like this is working properly:
```
  list(payload: any = {}): Observable<any> {
    payload = { ...payload, inner_param: this._someService.getObservable().value };
    return this._listEntity(payload);
  }

  @Cacheable({
    maxAge: 60000,
    maxCacheCount: 10,
    cacheBusterObserver: BustCache$.asObservable()
  })
  private _listEntity(payload: any = {}): Observable<any> {
    return this._http.post(`${environment.baseUrl}/some/api`, payload);
  }
```

**Comment by angelnikolov** [comment]
Yes, either that, or provide a custom `ICacheRequestResolver` to the decorator which might have access to the extra parameter you need. But I still think that your idea in the end is better :)

**Comment by marcio199226** [comment]
Yeah I think too that that the last one is the best option.

I have another question can I use multiple @CacheBuster on the same method?Or i have to use one only i then bust some other caches in actions where that method was used ?

**Comment by angelnikolov** [comment]
You can decorate the method with as many decorators as you want, but I would rather suggest that you combine two cache buster subjects into one stream and provide that to your @Cacheable-decorated methods.

**Comment by marcio199226** [comment]
Ok I should merge it by merge operator or concat ? The cache shoulds bust as soon as one of them emit new value

**Comment by marcio199226** [comment]
Hi @angelnikolov can you show an example how to merge to subject for CacheBuster ?

**Comment by angelnikolov** [comment]
@marcio199226 `cacheBusterObserver: merge(cacheBusterSubject1, cacheBusterSubject2)`

**Comment by marcio199226** [comment]
Thx I will try it, vs code highlight it as error so i thought that merging is not enough

**Comment by angelnikolov** [comment]
It must be `cacheBusterObserver: merge(cacheBusterSubject1.asObservable(), cacheBusterSubject2.asObservable())`, sorry :)
