### ISSUE TITLE
Ability to pass a custom JSON.stringify replacer

### ISSUE THREAD

**Issue by SansDK** [angelnikolov/ngx-cacheable#53]
Hi there,

I'm currently having an issue because of a circular structure in an object from another library (which should be cached).
This is easy to fix I could pass a stringify replacer, because I could then ignore the recursive property.

I couldn't find documentation on how to do this currently and I also didn't see an existing issue on this, so I made a new one.

Any help would be appreciated.
Thanks!

**Comment by angelnikolov** [comment]
@SansDK I actually had a branch on this but got rid off it for some reason. Will take a look over the weekend, thanks :)

**Comment by SansDK** [comment]
Great, thanks for the quick reply!

**Comment by SansDK** [comment]
Solved by #55 🎉
