### ISSUE TITLE
reload data when cacheBusterNotifier is called

### ISSUE THREAD

**Issue by williamxsp** [angelnikolov/ngx-cacheable#58]
When I save some data Id like that my informations get updated automatically.
Im doing the following:
   
```
get(pessoaId): Observable<Array<VideoModel>> {
        return merge(of([]), cacheBuster$).pipe(
            switchMap(() => {
                return this.http.get(`${this.baseUrl}/${pessoaId}`);
            })
        );
    }

 @CacheBuster({
        cacheBusterNotifier: cacheBuster$
    })
    add(video: VideoModel): Observable<VideoModel> {}
```

But im not sure if this is the best way to accomplish this.
Do you have any idea?

**Comment by angelnikolov** [comment]
Hey @williamxsp. Thanks for the question. You are on the right path, with the cache buster.
What you need to do so the cache is evicted successfully, is to just decorate your `get` method like:
```
@Cacheable({
    cacheBusterObserver: cacheBuster$.asObservable()
})
get(pessoaId): Observable<Array<VideoModel>> {
        return of([]).pipe(
            switchMap(() => {
                return this.http.get(`${this.baseUrl}/${pessoaId}`);
            })
        );
    }
```
Also, is there a reason that you need this `of([])` and a `switchMap`?

**Comment by angelnikolov** [comment]
@williamxsp 🏓

**Comment by williamxsp** [comment]
Thanks @angelnikolov .
Sorry for the late reply :)
