### ISSUE TITLE
Update rxjs peer dependency

### ISSUE THREAD

**Issue by yarrgh** [angelnikolov/ngx-cacheable#6]
When trying to update my packages via `ng update @angular/core` I get the following error:

> Package "ngx-cacheable" has an incompatible peer dependency to "rxjs" (requires "6.2.0", would install "6.2.2")

Can you update package.json to use any version of rxjs 6?

Something like:
```json
"peerDependencies": {
  "rxjs": "^6.2.0"
},
```

**Comment by angelnikolov** [comment]
Sure thing, I will update that over the weekend. Thanks for reporting!
