### ISSUE TITLE
Don't cache if response is empty

### ISSUE THREAD

**Issue by Patricksirich** [angelnikolov/ngx-cacheable#61]
Hi!
First of: I freaking love this package, thank you for sharing it!!!

And now to the issue:
I currently have an issue where if the response is empty (no errors, just an empty response), the data is still cached.

It is highly unlikely that the API is returning an empty response, but it can happen.

I am already doing checks on empty data, wrong data, etc.

I would like to avoid busting the cache if the response is empty.
Is there a clever way to ensure that the response is not saved if it is empty?
And maybe the possibility of adding this as a configuration in the future?

**Comment by angelnikolov** [comment]
Hey @Patricksirich, thanks for your kind words!
You can do this right now by passing a `shouldCacheDecider` to the decorator :)

**Comment by Patricksirich** [comment]
Thanks for the quick reply!
What value should I give the shouldCacheDecider? Can't really seem to figure it out 😄

**Comment by angelnikolov** [comment]
It's a callback which takes the response and based on it will decide to cache it or not.
For example, you could pass it as :
`shouldCacheDecider: response => response.length`
which would tell it to only cache the response if it is a non-empty array.

**Comment by Patricksirich** [comment]
That makes perfect sense, works like a charm, thanks!

**Comment by Patricksirich** [comment]
It doesn't seem to be working when maxCacheCount has been set.
Currently my decorator looks like: 

```
  @Cacheable({
    maxCacheCount: 3,
    maxAge: 300000,
    slidingExpiration: true,
    shouldCacheDecider: response => response.length
  })
```

but it does work on:

```
@Cacheable({
    maxAge: 300000,
    slidingExpiration: true,
    shouldCacheDecider: response => response.length
  })
```
