### ISSUE TITLE
How to use ngx-cacheable in server side pagination

### ISSUE THREAD

**Issue by ravi8194** [angelnikolov/ngx-cacheable#62]
I am building a app in which i am doing server side pagination by calling a same REST API with different query string on page change event. can i use this library to cache the response of previous pages so that if i go back to previous page , no API call made.

**Comment by angelnikolov** [comment]
@ravi8194 You can use the `maxCacheCount` parameter to support multiple caches per decorated method.
Check the [documentation](https://github.com/angelnikolov/ngx-cacheable#configuration).
