### ISSUE TITLE
import globalCacheBusterNotifier

### ISSUE THREAD

**Issue by khalilchoudhry** [angelnikolov/ngx-cacheable#67]
Hi,

So it's written on Readme.md that to import globalCacheBusterNotifier do:

import { globalCacheBusterNotifier } from './cacheable.decorator';

but this does not correctly import it. This does:

import { globalCacheBusterNotifier } from 'ngx-cacheable';

Great Library!

**Comment by angelnikolov** [comment]
@khalilchoudhry Thanks for reporting. Will update the readme :)

**Comment by angelnikolov** [comment]
Fixed by https://github.com/angelnikolov/ngx-cacheable/commit/3ab712dd675bbf1c67d6fd53237839cc5197237d
