### ISSUE TITLE
shouldCacheDecider in GlobalConfig

### ISSUE THREAD

**Issue by krogh** [angelnikolov/ngx-cacheable#68]
First of all, thank you for this very nice library!
I would like to apply a global shouldCacheDecider policy.
 shouldCacheDecider exists in the interface ICacheConfig but not in the GlobalCacheConfig.
Is this deliberate or a missing setting?  The Readme indicates it should be in the GlobalCacheConfig as well.
I can see there has been a discussion of global versus local config
https://github.com/angelnikolov/ngx-cacheable/issues/57
If shouldCacheDecider should be included I could make a pull request based on #57 to ease your work. I just wanted to hear your intentions first 
Best wishes and thank you
Michael

**Comment by angelnikolov** [comment]
@krogh Yeah, I must have forgotten adding that option to the global config. If you wish, you can make a PR and I will publish :)
Otherwise, I can do it in the next couple of days.
Thanks!

**Comment by krogh** [comment]
I will leave you to it then :-)
Thank you!

**Comment by krogh** [comment]
I actually had some time to tried it out  See the pull request
