### ISSUE TITLE
Caching distinct function results

### ISSUE THREAD

**Issue by fabioseno** [angelnikolov/ngx-cacheable#76]
Hi, I have two methods under the same service as below:

```
@Cacheable({
    cacheBusterObserver: myCacheBuster
})
listAll() {
    // return response data here
}

@Cacheable({
    cacheBusterObserver: myCacheBuster
})
list(filter) {
    // return filtered response data
}
```

The cache is only working if I hit subsequent calls to the same function. By having different functions, wasn't it supposed to have both results cached?

Apparently it works if I set the maxCacheCount to more than 1, but I understand that it should affect only combinations of cache under the same function. Am I right?

```
GlobalCacheConfig.maxCacheCount = 2;
````

Thanks!

**Comment by angelnikolov** [comment]
Not sure I understand. Both methods are independent in terms of caching.
If you call once listAll, you obviously wont' have cached results. Every other call of the same parameters will be. Same for `list`

**Comment by fabioseno** [comment]
They are independent functions, but they are not behaving as expected.

The behaviour:
1) Call **listAll** function -> executes HTTP request
2) Call **listAll** function again -> Data from cache (OK)
3) Call **list** function with some param -> executes HTTP request
4) Call **listAll** function -> executes HTTP request (ERROR).

**Comment by deyanpeychev00** [comment]
@fabioseno just curious, how do you check whether data is returned from cache or not?

**Comment by angelnikolov** [comment]
@fabioseno Can you provide an example in stackblitz?
Also, why do you need the `cacheBusterObservers`?

**Comment by angelnikolov** [comment]
@fabioseno Can you provide more information?

**Comment by fabioseno** [comment]
@deyanpeychev00 I just got some time to get back to this issue and realized it's working as expected now! I created a stackblitz (https://stackblitz.com/edit/angular-vzxqvv) and everything is alright.

Thank you all!

**Comment by angelnikolov** [comment]
Closing as resolved.
