### ISSUE TITLE
Bust cache from a specific function only

### ISSUE THREAD

**Issue by deyanpeychev00** [angelnikolov/ngx-cacheable#78]
Really like your project and the fact that it's a Bulgarian one!

Just a question: Having read the documentation and found that the cache can be busted using:

```javascript
import { globalCacheBusterNotifier } from './cacheable.decorator';
 
globalCacheBusterNotifier.next();
```

Is there a way that I can bust the cache only for a specific http request?

**Comment by angelnikolov** [comment]
Yes, you can provide a `cacheBusterNotifier: subject` in the `@Cacheable` config and next on it when you want a method's cache to be evicted.
https://github.com/angelnikolov/ngx-cacheable#cache-busting

**Comment by deyanpeychev00** [comment]
Just checked that, but I seem to get an error: 

Argument of type '{ cacheBusterNotifier: Subject<void>; }' is not assignable to parameter of type 'IObservableCacheConfig'.
      Object literal may only specify known properties, and 'cacheBusterNotifier' does not exist in type 'IObservableCacheConfig'.

Here is how I have implemented it:

```javascript
const allUsersCacheBuster$ = new Subject<void>();
```
```javascript
  @Cacheable({
    cacheBusterObserver: allUsersCacheBuster$
  })
  getAllUsers(query): Observable<HttpResponse<any>> {
    // gets data for users
  }
```
```javascript
  @Cacheable({
    cacheBusterNotifier: allUsersCacheBuster$
  })
  createUser(userData): Observable<any> {
    // creates new user
  }
```

**Comment by deyanpeychev00** [comment]
Also another question:

Is there a way to remove cache for a specific http request using the `globalCacheBusterNotifier`? In my case, I want to remove the cache related to the request that fetches the user's personal information once the user logs out.

**Comment by deyanpeychev00** [comment]
**Update:**

Ignore my comment with the error message, just made it work with removing the `cacheBusterNotifier` property from the `@Cacheable()` decorator and invoking `allUsersCacheBuster$.next()` in the methods that I want to clear the specific cache.

The issue can now be marked as closed or remain here if considered as helpful to someone. :)

**Comment by dmbaker90** [comment]
Maybe this should be documented.  I tried cacheBusterNotifier as well like the documentation and it didn't work.  

Does not work:
```
@Cacheable({
   cacheBusterNotifier: allUsersCacheBuster$
  })
  createUser(userData): Observable<any> {
    // creates new user
    return EMPTY;
  }
```

Works:
```
  createUser(userData): Observable<any> {
    allUsersCacheBuster$.next();
    return EMPTY;
  }
```
