### ISSUE TITLE
Where does this cache stores data?Is there any way to persist data even after refresh?

### ISSUE THREAD

**Issue by gdgagan696** [angelnikolov/ngx-cacheable#82]
Hi,

- Is there anyway to persist data even after page refresh?

- Where does this cache stores data as I couldn't find it in browser cache?

I have worked this way but its not working.

- Can you tell me whats the issue in this as it shows cacheBuster$ undefined when getUser() is called.

export class UserService {
  
  cacheBuster$ = new Subject<any>();
  URL="http://localhost:8030/users/";

  constructor(private httpClient:HttpClient) { }

  @Cacheable({
    cacheBusterObserver: this.cacheBuster$.asObservable()
  })
  getUser(id:number){
    return this.httpClient.get<any>(this.URL.concat(`getUser/${id}`)).pipe(tap(data=>{
      this.cacheBuster$.next(data);
    }));
  }
  @CacheBuster({
    cacheBusterNotifier: this.cacheBuster$s
  })
  updateUser(id:number){
    return this.httpClient.put(this.URL.concat(`updateUser/${id}`),{});
  }

**Comment by angelnikolov** [comment]
* Is there anyway to persist data even after page refresh?
- Yes, use DOMStorageStrategy. Find more about it in the readme.
* Where does this cache stores data as I couldn't find it in browser cache?
- The default storage strategy is `InMemoryStorageStrategy` which stores everything in-memory through a closure.
* Can you tell me whats the issue in this as it shows cacheBuster$ undefined when getUser() is called.
- Typescript decorators are static and they can't refer anything from the instance. That said, you need to take our your cache buster from the class and put it somewhere outside of it.
Foor example `const cacheBuster$ = new Subject()`;

**Comment by gdgagan696** [comment]
Hy Thanks. It worked.
I got some more issues.
I agree with this.The default storage strategy is InMemoryStorageStrategy which stores everything in-memory through a closure.

- But where I can find the data? In disk or at any other place?can you specify path where I can find data?

Also, DOMStorageStrategy worked for me.Thanks for that.

- Can I update cache data if it get changed ? Like in case of redis cache on server side, I am able to update cache data if user tries to update data.

For now in updateUser(id:number) method,I am deleting data from cache,It will be much better if somehow I am able to update data in cache.That will increase performance more.

 @Cacheable({
    maxCacheCount: 2,
    cacheBusterObserver: cacheBuster$.asObservable()
  })
  getUser(id:number){
    return this.httpClient.get<any>(this.URL.concat(`getUser/${id}`));
  }
  @CacheBuster({
    cacheBusterNotifier: cacheBuster$
  })
  updateUser(id:number){
    return this.httpClient.put(this.URL.concat(`updateUser/${id}`),{});
  }

**Comment by angelnikolov** [comment]
* But where I can find the data? In disk or at any other place?can you specify path where I can find data?
There isn't a way to find the data for the `InMemoryStorageStrategy`.
For the `DOMStorageStrategy`, you will normally find it under the `CACHE_STORAGE` localStorage key.

**Comment by gdgagan696** [comment]
Thanks @angelnikolov .
