### ISSUE TITLE
How to override default values from custom config settings?

### ISSUE THREAD

**Issue by mendezgabriel** [angelnikolov/ngx-cacheable#9]
Hi,

This is not an issue but more of a query since I'd like to pass some values to the Cacheable decorator dynamically. These would be defined in a config file and converted into an object. Essentially I have a service which contains several methods I'd like to cache like this:
`...
@Cacheable({
maxAge: this.config.cacheExpirationTimeInMilliseconds
})
    getCountries() {
        return this.http.get("api/Countries");
    }
...
`
I'm struggling to do that, since I always get an `undefined` reference on the `config` object. What should be the proper way to do this? Or better yet, how can I override default values being used by the decorator and what are those values?

Thanks in advance.

**Comment by ThibaudAV** [comment]
Why don't you use Angular environment variables ?

**Comment by mendezgabriel** [comment]
It's a legacy app and I am making some performance improvements, not too much room for refactoring. Would you give me an example of how it would work with environment variables?

**Comment by mendezgabriel** [comment]
Thanks! The second article gave me some ideas 👍
